name: service-instance_$GUID
releases:
{% for managed_service_release in context['managed_services_release'] %}
- name: {{managed_service_release['name']}}
  version: dev.42
{% endfor %}
stemcells:
- alias: only-stemcell
  os: ubuntu
  version: "2"
instance_groups:
{% for vm in context['vms'] %}
- name: {{ vm['name']}}
  instances: 1
  jobs:
  {% for jobType in vm['job_types'] %}
  - name: {{jobType['name']}}
    release: {{context['job2release_lookup_map'][jobType['name']]}}
  {% endfor %}
  properties:
    cf:
      app_domains: 
      - test-route.bosh-lite.com
      nats:
        host: 10.244.0.6
        password: nats
        port: 4222
        username: nats
    network: example-network  
    address: test-{{vm['name']}}-route
    {% for jobType in vm['job_types'] %}
    {{jobType['nameInGo']}}_address: test-{{jobType['name']}}-route
    {{jobType['nameInGo']}}_password: BdUvmQueOLCemBXlkijp
    {{jobType['nameInGo']}}_username: XcrexMfLWeQU
    {% endfor %}
    
  vm_type: small
  stemcell: only-stemcell
  persistent_disk_type: ten
  azs:
  - example-az
  networks:
  - name: example-network
{% endfor %}
update:
  canaries: 1
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000
  max_in_flight: 2
  serial: true
properties:
  cf:
    apps_domain: test-route.bosh-lite.com
  jobType1: null
  jobType2: null
